#!/bin/bash

echo "This script runs before compiling the main program for Mac OS with alternative legacy flags, and can be used to compile a library or do anything before building for Mac OS with alternative legacy flags."