#!/bin/bash

echo "This script runs before compiling the main program for the host OS and 32 bit arch, and can be used to compile a library or do anything before building for the host OS and 32 bit arch."