#!/bin/bash

# EzRe build script
version="1.0.7"
program="ezre"
release_name="$program-v$version"
release_files="readme.md license.md changelog.md template-files example ezre"

cd "$(dirname "$0")"

version=$version
rm -rf "$release_name" "$release_name".zip "$release_name".deb *.rpm
make -C example clean-build

if [ "$1" == "clean" ]; then
    exit 0
fi

if sed --version >/dev/null 2>&1; then
    echo "Info: using GNU sed"
    sed_args="-i"
else
    echo "Info: using BSD sed"
    sed_args="-i '' -E"
fi

sed "$sed_args" "s|^VERSION=.*|VERSION=$version|" control
sed "$sed_args" "s|Version:.*|Version: $version|" ezre.spec

mkdir -p "$release_name"/usr/bin
mkdir -p "$release_name"/usr/share/ezre
mkdir -p "$release_name"/DEBIAN
cp control "$release_name"/DEBIAN
cp -r ezre "$release_name"/usr/bin
cp template-files/* "$release_name"/usr/share/ezre
dpkg-deb --build "$release_name"

rm -rf "$release_name"

mkdir "$release_name"
cp -r ${release_files} "$release_name"

chmod -R 777 "$release_name"
zip -r "$release_name".zip "$release_name"

rm -rf "$release_name"/*

rm -rf rpm-tmp
mkdir -p rpm-tmp/RPMS rpm-tmp/SPECS rpm-tmp/SOURCES rpm-tmp/BUILD
cp ezre.spec rpm-tmp/SPECS/ezre.spec
cp ezre rpm-tmp/SOURCES/ezre
cp -r template-files rpm-tmp/SOURCES/
rpmbuild -bb --target noarch rpm-tmp/SPECS/ezre.spec --define "_topdir $PWD/rpm-tmp"
mv rpm-tmp/RPMS/noarch/*.rpm .
rm -rf rpm-tmp
