#!/bin/bash

# EzRe build script

set -e
version="v1.0.1"
program="ezre"
release_name="$program-$version"
release_files="readme.md license.md changelog.md control-i386 control-x86_64 variables.mk Makefile example"

cd "$(dirname "$0")"
rm -rf "$release_name" "$release_name".zip

if [ "$1" == "clean" ]; then
    make -C example clean-build
    exit 0
fi

mkdir "$release_name"
cp -r ${release_files} "$release_name"

chmod -R 777 "$release_name"
zip -rq "$release_name".zip "$release_name"
rm -rf "$release_name"
