#!/bin/bash

# EzRe build script
version="v1.0.2"
program="ezre"
release_name="$program-$version"
release_files="readme.md license.md changelog.md template-files example ezre ezre-dl"

cd "$(dirname "$0")"
rm -rf "$release_name" "$release_name".zip "$release_name".deb

if [ "$1" == "clean" ]; then
    make -C example clean-build
    exit 0
fi

mkdir -p "$release_name"/usr/bin
mkdir -p "$release_name"/usr/share/ezre
mkdir -p "$release_name"/DEBIAN
cp control "$release_name"/DEBIAN
cp -r ezre ezre-dl "$release_name"/usr/bin
cp template-files/* "$release_name"/usr/share/ezre
dpkg-deb --build "$release_name"

rm -rf "$release_name"

mkdir "$release_name"
cp -r ${release_files} "$release_name"

chmod -R 777 "$release_name"
zip -r "$release_name".zip "$release_name"

rm -rf "$release_name"/*
