#!/bin/bash

script_dir=$(dirname "$0")
ezre_files=""$script_dir"/template-files"
answered_yes=false
version=1.0.8

echo -e "EzRe v"$version"\n(C) 2023-2025, Alex Free (3-BSD)\n"

if [ ! -e "$ezre_files" ]; then

    if [ ! -e "/usr/share/ezre" ]; then
        echo "Error: Neither "\"$script_dir/template-files"\" or "\"/usr/shar/ezre"\" exist."
        exit 1
    else
        ezre_files="/usr/share/ezre"
    fi
fi

echo "Info: Ezre template files directory: "$ezre_files""

if sed --version >/dev/null 2>&1; then
    echo "Info: using GNU sed."
    sed_args="-i"
else
    echo "Info: using BSD sed."
    sed_args="-i '' -E"
fi

if [ "$#" -eq 2 ] && [ "$1" == "-u" ]; then
        
    if [ -f "control-i386" ]; then
        sed "$sed_args" "s|^VERSION=.*|VERSION=$VERSION|" control-i386
        echo "control-i386 has been updated"
    fi

    if [ -f "control-x86_64" ]; then
        sed "$sed_args" "s|^VERSION=.*|VERSION=$VERSION|" control-x86_64
        echo "control-x86_64 has been updated"
    fi

    if [ -f "ezre.spec" ]; then
        # Add v for naming convention.
        sed "$sed_args" "s|Version:.*|Version: v$VERSION|" ezre.spec
        echo "ezre.spec has been updated"
    fi

    exit 0

elif [ "$#" -eq 1 ] && [ "$1" == "-u" ]; then
        echo "Error: you must provide 2 arguments to update the version number."
        exit 1
elif [ "$#" -eq 1 ] && [ "$1" == "-y" ]; then
        answered_yes=true
fi

if [ "$answered_yes" = false ]; then
    echo -e "Info: to avoid prompts to overwrite existing files, specify -y in the future."    
fi

overwrite_file_with_prompt() {
    file="$1"

    if [ -e "$file" ]; then
        echo -e "\nInfo: \"$file\" already exists in the current working directory."

        if [ "$answered_yes" = "false" ]; then
            read -p "Overwrite \"$file\" with \"$ezre_files/$file\"? (Y/n) " -n 1 -r
            echo
        fi
    fi

    if [[ $REPLY =~ ^[Yy]$ ]] || [ "$answered_yes" = "true" ] || [ ! -e "$file" ]; then
        cp -v "$ezre_files/$file" .
    fi
}

# Example usage
overwrite_file_with_prompt "Makefile"
overwrite_file_with_prompt "build.md"
overwrite_file_with_prompt "control-i386"
overwrite_file_with_prompt "control-x86_64"
overwrite_file_with_prompt "ezre.spec"

# variables.mk
if [ -e "variables.mk" ]; then
    echo -e "\nInfo: \"variables.mk\" already exists in the current working directory and will be updated."
    
    while IFS='=' read -r key value; do
        # Ignore lines that are empty or start with '#' (comments)
        if [[ -z "$key" || "$key" =~ ^\s*# ]]; then
            continue
        fi

        # Remove any trailing whitespace from the value
        value=$(echo "$value" | xargs)
        # Assign the value to the bash variable
        export "$key"="$value"
    done < "variables.mk"
    
    cp -v "$ezre_files"/variables.mk .

    # Transfer values over to new variables.mk
    sed "$sed_args" "s|^PROGRAM=.*|PROGRAM=$PROGRAM|" variables.mk
    sed "$sed_args" "s|^VERSION=.*|VERSION=$VERSION|" variables.mk
    sed "$sed_args" "s|^SOURCE_FILES=.*|SOURCE_FILES=$SOURCE_FILES|" variables.mk

    sed "$sed_args" "s|^RELEASE_BASE_NAME=.*|RELEASE_BASE_NAME=$RELEASE_BASE_NAME|" variables.mk
    sed "$sed_args" "s|^RELEASE_FILES=.*|RELEASE_FILES=$RELEASE_FILES|" variables.mk

    sed "$sed_args" "s|^SOFTWARE_DESCRIPTION=.*|SOFTWARE_DESCRIPTION=$SOFTWARE_DESCRIPTION|" variables.mk
    sed "$sed_args" "s|^YOUR_NAME=.*|YOUR_NAME=$YOUR_NAME|" variables.mk
    sed "$sed_args" "s|^WEBSITE=.*|WEBSITE=$WEBSITE|" variables.mk
    sed "$sed_args" "s|^LICENSE=.*|LICENSE=$LICENSE|" variables.mk

    sed "$sed_args" "s|^BUILD_DEPENDS_APT=.*|BUILD_DEPENDS_APT=$BUILD_DEPENDS_APT|" variables.mk
    sed "$sed_args" "s|^BUILD_DEPENDS_DNF=.*|BUILD_DEPENDS_DNF=$BUILD_DEPENDS_DNF|" variables.mk
    sed "$sed_args" "s|^BUILD_DEPENDS_MACPORTS=.*|BUILD_DEPENDS_MACPORTS=$BUILD_DEPENDS_MACPORTS|" variables.mk

    sed "$sed_args" "s|^COMPILER=.*|COMPILER=$COMPILER|" variables.mk
    sed "$sed_args" "s|^COMPILER_MAC=.*|COMPILER_MAC=$COMPILER_MAC|" variables.mk
    sed "$sed_args" "s|^COMPILER_MAC_LEGACY=.*|COMPILER_MAC_LEGACY=$COMPILER_MAC_LEGACY|" variables.mk
    sed "$sed_args" "s|^COMPILER_WINDOWS_I686=.*|COMPILER_WINDOWS_I686=$COMPILER_WINDOWS_I686|" variables.mk
    sed "$sed_args" "s|^COMPILER_WINDOWS_X86_64=.*|COMPILER_WINDOWS_X86_64=$COMPILER_WINDOWS_X86_64|" variables.mk

    sed "$sed_args" "s|^COMPILER_FLAGS=.*|COMPILER_FLAGS=$COMPILER_FLAGS|" variables.mk
    sed "$sed_args" "s|^COMPILER_FLAGS_MAC=.*|COMPILER_FLAGS_MAC=$COMPILER_FLAGS_MAC|" variables.mk
    sed "$sed_args" "s|^COMPILER_FLAGS_MAC=LEGACY.*|COMPILER_FLAGS_MAC_LEGACY=$COMPILER_FLAGS_MAC_LEGACY|" variables.mk
    sed "$sed_args" "s|^COMPILER_FLAGS_WINDOWS_I686=.*|COMPILER_FLAGS_WINDOWS_I686=$COMPILER_FLAGS_WINDOWS_I686|" variables.mk
    sed "$sed_args" "s|^COMPILER_FLAGS_WINDOWS_X86_64=.*|COMPILER_FLAGS_WINDOWS_X86_64=$COMPILER_FLAGS_WINDOWS_X86_64|" variables.mk
    sed "$sed_args" "s|^COMPILER_FLAGS_LINUX_I386=.*|COMPILER_FLAGS_LINUX_I386=$COMPILER_FLAGS_LINUX_I386|" variables.mk

    sed "$sed_args" "s|^LDFLAGS=.*|LDFLAGS=$LDFLAGS|" variables.mk
    sed "$sed_args" "s|^LDFLAGS_MAC=.*|LDFLAGS_MAC=$LDFLAGS_MAC|" variables.mk
    sed "$sed_args" "s|^LDFLAGS_MAC_LEGACY=.*|LDFLAGS_MAC_LEGACY=$LDFLAGS_MAC_LEGACY|" variables.mk
    sed "$sed_args" "s|^LDFLAGS_WINDOWS_I686=.*|LDFLAGS_WINDOWS_I686=$LDFLAGS_WINDOWS_I686|" variables.mk
    sed "$sed_args" "s|^LDFLAGS_WINDOWS_X86_64=.*|LDFLAGS_WINDOWS_X86_64=$LDFLAGS_WINDOWS_X86_64|" variables.mk

    sed "$sed_args" "s|^STRIP=.*|STRIP=$STRIP|" variables.mk
    sed "$sed_args" "s|^STRIP_MAC=.*|STRIP_MAC=$STRIP_MAC|" variables.mk
    sed "$sed_args" "s|^STRIP_MAC=LEGACY.*|STRIP_MAC_LEGACY=$STRIP_MAC_LEGACY|" variables.mk
    sed "$sed_args" "s|^STRIP_WINDOWS_I686=.*|STRIP_WINDOWS_I686=$STRIP_WINDOWS_I686|" variables.mk
    sed "$sed_args" "s|^STRIP_WINDOWS_X86_64=.*|STRIP_WINDOWS_X86_64=$STRIP_WINDOWS_X86_64|" variables.mk

    sed "$sed_args" "s|^BUILD_DIR=.*|BUILD_DIR=$BUILD_DIR|" variables.mk

    echo -e "\nUpdated variables.mk."

    # RPM
    sed "$sed_args" "s|your_executable|$PROGRAM|" ezre.spec
    sed "$sed_args" "s|License:*|License: $LICENSE|" ezre.spec
    sed "$sed_args" "s|Name:*|Name: $RELEASE_BASE_NAME|" ezre.spec
    sed "$sed_args" "s|Summary:*|Summary: $SOFTWARE_DESCRIPTION|" ezre.spec
    sed "$sed_args" "/%description/{n; s|^|$SOFTWARE_DESCRIPTION\n|;}" ezre.spec
    # Add v for naming convention.
    sed "$sed_args" "s|Version:*|Version: v$VERSION|" ezre.spec
    sed "$sed_args" "s|URL:*|URL: $WEBSITE|" ezre.spec
    sed "$sed_args" "s|Packager:*|Packager: $YOUR_NAME|" ezre.spec

    echo "Updated ezre.spec."

    # DEB
    sed "$sed_args" "s|^Package:*|Package: $RELEASE_BASE_NAME|" control-i386
    sed "$sed_args" "s|Description:*|Description: $SOFTWARE_DESCRIPTION|" control-i386
    sed "$sed_args" "s|Version:*|Version: $VERSION|" control-i386
    sed "$sed_args" "s|Homepage:*|Homepage: $WEBSITE|" control-i386
    sed "$sed_args" "s|Maintainer:*|Maintainer: $YOUR_NAME|" control-i386

    echo "Updated control-i386."

    sed "$sed_args" "s|^Package:*|Package: $RELEASE_BASE_NAME|" control-x86_64
    sed "$sed_args" "s|Description:*|Description: $SOFTWARE_DESCRIPTION|" control-x86_64
    sed "$sed_args" "s|Version:*|Version: $VERSION|" control-x86_64
    sed "$sed_args" "s|Homepage:*|Homepage: $WEBSITE|" control-x86_64
    sed "$sed_args" "s|Maintainer:*|Maintainer: $YOUR_NAME|" control-x86_64

    echo "Updated control-x86_64."
else
    cp -v "$ezre_files"/variables.mk .
fi
